server:
  port: 9001
spring:
  profiles:
    active: dev
  application:
    name: bakuman-test-service
#    datasource数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://linux.bakuman.cn:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: xiaojiandnf
#    redis数据源
  redis:
    host: linux.bakuman.cn
    port: 6379
    database: 0
    password:
#      nacos服务注册
  cloud:
    nacos:
      discovery:
        server-addr: http://linux.bakuman.cn
        namespace: bakuman-${spring.profiles.active}
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      #        nacos配置中心
#      config:
#        server-addr: http://linux.bakuman.cn
#        file-extension: yaml
#        group: DEFAULT_GROUP
#        namespace: by-${spring.profiles.active}


