server:
  port: 9001
service-url:
  user-service: http://localhost:9001
spring:
  profiles:
    active: dev
  application:
    name: bakuman-gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://linux.bakuman.cn
        namespace: bakuman-${spring.profiles.active}
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
    gateway:
#      开启服务名动态路由
      discovery:
        locator:
          enabled: true
      routes: #配置路由规则
        - id: test-route
          uri: lb://bakuman-test-service
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1

#白名单
